#!/usr/bin/env bash
# block all incoming traffic
# exceptions TCP ports: 22 (SSH), 80 (HTTP), 443 (HTTPS SSL)
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
