#!/usr/bin/env bash
# display To infinity and beyond indefinitely
# in between each iteration, add sleep 2
while true; do
trap "echo I am invincible!!!" SIGTERM
echo "To infinity and beyond"
sleep 2
done
