#!/usr/bin/env bash
# creates the file /var/run/holbertonscript.pid
# displays message when receiving SIGTERM
# displays message when receiving SIGINT
# delete the file and terminate itself when receiving SIGQUIT or SIGTERM
echo $$ > /var/run/holbertonscript.pid
while true; do
trap "echo I hate the kill command; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "echo Y U no love me?; rm /var/run/holbertonscript.pid; exit" SIGINT
echo "To infinity and beyond";
sleep 2;
done
