#!/usr/bin/env bash
# displays multiples of 3 and 5: "FizzBuzz"
# displays multiples of 3: "Fizz"
# displays multples of 5: "Buzz"
# else, display number

for ((i=1; i<=100; i++)); do
    if [ $((i % 15)) -eq 0 ]; then
	echo -e "FizzBuzz"
    elif [ $((i % 3)) -eq 0 ]; then
	echo -e "Fizz"
    elif [ $((i % 5)) -eq 0 ]; then
	echo -e "Buzz"
    else
	echo -e "$i"
    fi
done
