#!/usr/bin/env bash
# display "bad luck" for 4th iter, "good luck" for 8th
# "Holberton School" for others
i=1
while [ $i -le 10 ]; do
    if [[ $i = 4 ]]; then
      	echo "bad luck"
	i=$(( i+1 ))
    elif [[ $i = 8 ]]; then
	echo "good luck"
	i=$(( i+1 ))
    else
	echo "Holberton School"
	i=$(( i+1 ))
    fi
done
