#!/usr/bin/env bash
# display "bad luck from China" for 4th iter
# "bad luck from Japan" 9th
# "bad luck from Italy" 17th
# numbers for others
i=1
while [ $i -le 20 ]; do
    echo "$i"
    case $i in
	4)
      	    echo -e "bad luck from China"
	    ;;
	9)
	    echo -e "bad luck from Japan"
	    ;;
	17)
	    echo -e "bad luck from Italy"
	    ;;
    esac
    i=$(( i+1 ))
done
