#!/usr/bin/env bash
# display "bad luck from China" for 4th iter
# "bad luck from Japan" 9th
# "bad luck from Italy" 17th
# numbers for others
i=1
while [ $i -le 20 ]; do
    if [[ $i = 4 ]]; then
      	echo "bad luck from China"
	i=$(( i+1 ))
    elif [[ $i = 9 ]]; then
	echo "bad luck from Japan"
	i=$(( i+1 ))
    elif [[ $i = 17 ]]; then
	echo "bad luck from Italy"
	i=$(( i+1 ))
    else
	echo "$i"
	i=$(( i+1 ))
    fi
done
