#!/usr/bin/env bash
# display time for 12 hours and 59 minutes
# display "Hour: "
# disply minutes 1-59
i=0
while [ $i -lt 13 ]; do
      	echo "Hour: $i"
	i=$(( i + 1 ))
	j=1
	while [ $j -lt 60 ]; do
		echo "$j"
	        j=$(( j + 1 ))
	done
done
