#!/usr/bin/env bash
# use if, else: check if "holbertonschool" exists
# if file exists: "holbertonschool file exists"
# if file does not exist: "holbertonschool file does not exist"
FILE=holbertonschool
if [ -e "$FILE" ]; then
    echo "holbertonschool file exists"
    if [ -f "$FILE" ]; then
	echo "holbertonschool is a regular file"
    fi
    if [ -s "$FILE" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
