#! /usr/bin/env bash
# script configures an ubuntu server
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i -e "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
sed -i -e "\$a8.8.8.8\tfacebook.com\n" ~/hosts.new
cp -f ~/hosts.new /etc/hosts
