#!/usr/bin/env bash
shellcheck disable=SC2154
sudo apt-get update;
sudo apt-get install -y nginx;
sudo cp /etc/nginx/sites-avaiable/default /etc/nginx/sites-available/default.bak
sudo sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
