#!/usr/bin/env bash
shellcheck disable=SC2154
sudo apt-get update;
sudo apt-get install -y nginx;
sudo service nginx start
sudo sed -i "20i\        add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
