#!/usr/bin/env bash
# runs the nginx webserver as the 'nginx' user
sudo pkill -f apache2
sed -i '/#user www-data;/a user nginx;' /etc/nginx/nginx.conf
sudo sed -i 's/:80 /:8080 /g' /etc/nginx/sites-enabled/default
sudo service nginx restart
